### ISSUE TITLE
Broken accessor in merge queues

### ISSUE THREAD

**Issue by gisheri** [nrwl/nx-set-shas#111]
It appears one of the latest changes introduced some problematic logic in the merge queue event. Here's a screenshot of the error. We've been using this for several months, and this just started occuring today. We are using v3, rather than a pinned version, so we're automatically getting these updates. 

<img width="1165" alt="Screen Shot 2023-09-06 at 3 11 10 PM" src="https://github.com/nrwl/nx-set-shas/assets/4277439/8eb59cdd-7408-44fb-a0c5-afbdd4aaaedb">

**Comment by gisheri** [comment]
Probably from this https://github.com/nrwl/nx-set-shas/commit/8419441aae00f0d0c25bfd31c6fb2027c2a3631b. Adding `merge_group` to the include list, but then attempting to look in the pull_request context (which wouldn't be there for a merge group event)

**Comment by meeroslav** [comment]
Thank you for the quick report @gisheri. We will fix it ASAP. For the time being switch back to the previous version.

**Comment by rathpc** [comment]
I just came to report this as well so I am glad someone already did. Pinning a version will unfortunately not be a quick fix in my case because my org restricts actions to a defined list which we have specified this one as v3. I would need to make a special request to get v3.1 added in order to unblock all of our workflows.

@meeroslav Can I suggest in the meantime you can maybe push a revert commit while you fix the issue so that v3 tag is automatically reassociated with a stable version? Either that or short term tag v3 on a previous commit sha?

**Comment by augustoscher** [comment]
The same happening here:
<img width="1570" alt="image" src="https://github.com/nrwl/nx-set-shas/assets/9935397/4747b3d5-1022-4cc0-b212-48d52a0aeab2">

**Comment by meeroslav** [comment]
Fix is on the way. Sorry for this, folks!

**Comment by rathpc** [comment]
Thank you for the quick fix!
