### ISSUE TITLE
Error from `git diff --name-only --no-renames --relative `

### ISSUE THREAD

**Issue by enchorb** [nrwl/nx-set-shas#119]
Starting getting the below error on any versions `3.1.0+`, works fine on `3.0.2`

We force push to our deploy branches frequently - is this the cause? 

```
 Error: Command failed: git diff --name-only --no-renames --relative "sha1" "sha2"
fatal: bad object sha1

    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at parseGitOutput (/home/runner/work/node_modules/nx/src/utils/command-line-utils.js:234:41)
    at getFilesUsingBaseAndHead (/home/runner/work/node_modules/nx/src/utils/command-line-utils.js:231:12)
    at parseFiles (/home/runner/work/node_modules/nx/src/utils/command-line-utils.js:185:20)
    at getAffectedGraphNodes (/home/runner/work/node_modules/nx/src/command-line/affected/affected.js:85:151)
    at Object.affected (/home/runner/work/node_modules/nx/src/command-line/affected/affected.js:34:28) {
  status: 128,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 66 61 74 61 6c 3a 20 62 61 64 20 6f 62 6a 65 63 74 20 65 35 62 31 34 30 64 38 64 33 34 61 37 63 64 37 61 65 32 36 32 34 31 35 38 62 39 61 63 61 66 35 ... 9 more bytes>
  ],
  pid: 2319,
  stdout: <Buffer >,
  stderr: <Buffer 66 61 74 61 6c 3a 20 62 61 64 20 6f 62 6a 65 63 74 20 65 35 62 31 34 30 64 38 64 33 34 61 37 63 64 37 61 65 32 36 32 34 31 35 38 62 39 61 63 61 66 35 ... 9 more bytes>
```

**Comment by RobbyRabbitman** [comment]
Hi there, I observed the same behavior. To my understanding it is working as intended, since it stored the sha of the last succesful commit, which does not exist anymore, since you force pushed and erased the history. We have to tell this action to reset itself or point the base to the desired commit.

**Comment by meeroslav** [comment]
We also force push on our PRs often, so this should be fine.

There's likely something else off in your workflow. Can you provide the workflow here?

The action finds the last successful run whose commit exists (https://github.com/nrwl/nx-set-shas/blob/main/find-successful-workflow.ts#L191)

**Comment by JamesHenry** [comment]
@enchorb are the deploy branches you mention set to be your "main" branch for the purposes of the workflow? Please can you share your config?

@nirga also cited force pushing as being an issue on #79 

I am wondering if force pushing works fine on PRs @meeroslav but causes issues when it is the branch being identified as the main branch which is being force pushed to?

**Comment by enchorb** [comment]
They are not the `main` branch. For deploying to our development environment the branch is `dev` and for production it is `prod`. The setup for the actions step looks like:

```
      - name: Get SHAs (BASE & HEAD) For `nx affected`
        id: sha
        uses: nrwl/nx-set-shas@v3.0.2
        with:
          main-branch-name: ${{ needs.initialize.outputs.env }}
```

**Comment by JamesHenry** [comment]
Thanks @enchorb so the answer is actually, yes, in this case. What I said was:

> "main" branch for the purposes of the workflow

Not literally the branch called `main`.

As you can see here you are setting the `main-branch-name` input, so for the purpose of this workflow it is the "main" branch being used to compare against

**Comment by fmalcher** [comment]
I had the same problem: After force-pushing to `main` (yeah, we shouldn't be doing this 😏 ) the nx-cloud workflow failed since the sha referenced in `NX_BASE` didn't exist anymore.
I found this hacky workaround:
- Remove the workspace from Nx cloud.
- Connect the workspace again. This creates a new access token.
- Restart the last successful workflow run in GitHub Actions. It will fail because the access token changed.
- Since it failed, it is no longer the last successful run! 🥳 The workflow will take the previous run as the new base.

It just took me 1,5 hours to get there, so I hope it's helpful to anyone.
Biggest lesson to me is: never force-push to `main` (even though it was a personal project and nobody cares).

**Comment by JamesHenry** [comment]
We will now fallback to the previous commit (in the same way we do when a commit is missing entirely) when the BASE_SHA commit exists but is no longer associated with the main branch (meaning whatever you have set `main-branch-name` to be)
