### ISSUE TITLE
Document which app permissions are required in v2

### ISSUE THREAD

**Issue by alexberriman** [nrwl/nx-set-shas#14]
First off, thanks for this library - it's very useful.

From what I understand after quickly reading through the README, v1 of this library used git tags to infer the base and head values, whereas v2 uses the GIthub API.

Github allows you to override the permissions granted to the `GITHUB_TOKEN` within your workflow at both the top level and within a specific job. If you do override this value, it implicitly sets every value you don't specify to `none`. As per their own documentation, when overriding you want to provide the minimum amount of access required for your workflow to run.

It would be good to know which API/app scopes were required (or which API endpoints you were hitting) to know how to correctly configure the permissions. I dropped in a few I thought might be needed, only for the job to fail. I then thought to look through the code to identify which API endpoints you were hitting, but you only seem to publish the bundled `dist` directory.

v1 solves my use case for now so it's easier for me to just drop the version back and not worry about permissions, but it would be good to know going forward.

**Comment by sviatoslav-lebediev** [comment]
Hi, good question, I've had the same problem
for me, it works with this list of permissions

```yml
    permissions:
      actions: 'write'
      contents: 'write'
      id-token: 'write' --- this one I use for the `google-github-actions/auth@v0`
```

**Comment by meeroslav** [comment]
Hi @alexberriman, thank you for reaching out. 

We moved away from the v1 design as it was polluting the git codebase. The source code for accessing APIs is bundled in order to include all the dependencies (Github's @action and @octokit)

As you can see in the code at https://github.com/nrwl/nx-set-shas/blob/main/find-successful-workflow.js#L72 and https://github.com/nrwl/nx-set-shas/blob/main/find-successful-workflow.js#L80 these are the only two calls we do on top of running standard git commands like `merge-base` and `rev-parse` and accessing the context of the run.

In both calls to Octokit/action API, we use just `GET` so read permissions should be enough.

So you would need:
```yaml
permissions:
  actions: 'read'
  contents: 'read'
```

Feel free to create PR with this information added to the readme.
