### ISSUE TITLE
NX_HEAD has a random sha?

### ISSUE THREAD

**Issue by amuresia** [nrwl/nx-set-shas#17]
Hi there,

I am using nrwl/nx-set-shas@v2 and in the logs I can see the NX_BASE set to the correct commit and NX_HEAD set to a commit that does not exist anywhere in the tree. This is constantly reproducible. The `nx affected` command does seem to correctly identify changed apps but I would like to understand why NX_HEAD doesn't point to the actual head.
The action is triggered
```
on:
  pull_request:
    types: [ synchronize ]
```
Thank you!

**Comment by meeroslav** [comment]
Hi @amuresia, thank you for reporting the issue.

Can you tell me more about your workflow? Are you referring to `commit on main branch` or `merging the PR`?
We use standard `git rev-parse HEAD` so that should not return arbitrary/false information.

Can you run the following command with the given NX_HEAD and let me know what it returns:
```bash
git cat-file -p {your NX_HEAD sha}
```
 
 If it fails, then the commit is indeed non-existent. Otherwise, it should return the information about the commit.
 
 Please note if you (or someone in your team) use `git push --force` to override previous commits, that might explain why the commit doesn't exist.

**Comment by cormorando** [comment]
Hi,

I encountered the same issue and when ran `git cat-file -p {your NX_HEAD sha}` I got `fatal: Not a valid object name  {your NX_HEAD sha}`

**Comment by meeroslav** [comment]
Closing this as stale
