### ISSUE TITLE
BUG: Usage within a tag push is not working

### ISSUE THREAD

**Issue by chrisui** [nrwl/nx-set-shas#19]
If this action is run within a push tags github action event context then it fails to find previous success workflows.

I can validate that that there are definitely successful workflows. Worth noting that in the github ui for listing runs of a single workflow id you see the tag name and not the branch name like you do for branch pushes or pull request workflows.

![image](https://user-images.githubusercontent.com/1042432/152435642-f198576a-1839-4e35-9a22-03148ae2dba4.png)

```
Run nrwl/nx-set-shas@v2
  with:
    main-branch-name: main
    set-environment-variables-for-job: true
    error-on-no-successful-workflow: false
    last-successful-event: push
  env:
    NX_CLOUD_AUTH_TOKEN: ***
Run node $GITHUB_ACTION_PATH/dist/index.js *** main false push 

WARNING: Unable to find a successful workflow run on 'origin/main'
We are therefore defaulting to use HEAD~1 on 'origin/main'

NOTE: You can instead make this a hard error by settting 'error-on-no-successful-workflow' on the action in your workflow.
```

**Comment by meeroslav** [comment]
There are different reasons why your successful runs might not be found:
- Check was run against invalid workflow
- You were overriding the commits (e.g with force push) so commit shas from workflow history do not match the git history

Can you try to call the API directly and let me know what do you see?
```url
https://api.github.com/repos/{owner}/{repo}/actions/workflows/{workflow_file_name}/runs?event=push&status=success&branch={main_branch_name}
```

If there are successful workflow runs check the commit sha at `head_sha` for existence:
```bash
git cat-file -t {commit_sha}
```

If the response is `commit` then commit exists, otherwise you will get something like
```
fatal: git cat-file: could not get object info
```

e.g.
```bash
https://api.github.com/repos/meeroslav/linter-swc-test/actions/workflows/test.yml/runs?event=push&status=success&branch=main

git cat-file -t ef58b15dee5dec2313de33c190aea0bad42417
```

**Comment by amireldor** [comment]
Hey @meeroslav , I might be facing a similar issue and I used the GitHub API manually see the workflows returned for my repo.

Background: I have a private repo, I run CI for `prod` branch and I expect nx-set-shas to find the last successful workflow on `prod` yet it fails to find one.

Inspecting the result of the manual API call, in one of my "push" workflows to `prod`, I saw:

```
      "event": "push",
      "status": "completed",
      "conclusion": "success",
``` 

In your code, I see these lines:

```javascript
  const shas = await octokit.request(`GET /repos/${owner}/${repo}/actions/workflows/${workflow_id}/runs`, {
    owner,
    repo,
    branch,
    workflow_id,
    event: lastSuccessfulEvent,
    status: 'success'
  }).then(({ data: { workflow_runs } }) => workflow_runs.map(run => run.head_sha));
```

Note that you search for status: 'success' on a lastSuccessfulEvent, which is `push` in my case, but the status I saw in my GitHub API call is "completed" and the conclusion is "success". Maybe there's a mismatch in the parameters of your query?

I also ran the API from the previous comment (substituting the relevant values):

```
https://api.github.com/repos/{owner}/{repo}/actions/workflows/{workflow_file_name}/runs?event=push&status=success&branch={main_branch_name}
```

And also
```
https://api.github.com/repos/{owner}/{repo}/actions/workflows/{workflow_file_name}/runs?event=push
```

And both returned **No workflows**. Isn't that strange? Just to emphasize, I _do_ get my workflows when I run it without the URL search params, that's where I saw the the first snippet I pasted above.

I am suspecting different `status` value returned for 'push' vs. 'PRs' as IIRC you wrote you didn't test this thoroughly with pushes as you mostly use PRs.

**Comment by amireldor** [comment]
Hello @meeroslav, do you still need more info? Anything else I can try helping with or more information to provide?

**Comment by meeroslav** [comment]
@amireldor, this workflow only runs for `push`. For PRs we take the main branch's branching point as `BASE` and the last commit as `HEAD`. 

Can you try running the same API call but with `status=completed`?:
```
https://api.github.com/repos/{owner}/{repo}/actions/workflows/{workflow_file_name}/runs?event=push&status=completed&branch={main_branch_name}
```

Does that return any values?
When you say manual API call, what does that mean? What parameters do you pass?

**Comment by amireldor** [comment]
Hi @meeroslav, thanks for the response. By "manual API call" I mean I call it from the CLI with `curl`. I've just ran the query you asked for and passed the following parameters:

    .../runs?event=push&status=success&branch=prod
    # and also:
    .../runs?event=push&status=completed&branch=prod

(I currently wish to build and deploy by pushing to my `prod` branch)

The first one (with `status=success`) is the correct one as I only get workflows with `"conclusion": "success"`, so I guess your code is correct.

I think I have a different problem and I don't want to hijack this issue thread. Sorry for that.

I'm getting this message in GitHub actions. I'll open another issue if I don't manage to solve this.

```
WARNING: Unable to find a successful workflow run on 'origin/prod'
We are therefore defaulting to use HEAD~1 on 'origin/prod'
```

(I do have successful workflows on that branch)

Thanks.

**Comment by chrisui** [comment]
Also adding that there are issues when history is re-written from a rebase. Appears this action gets a false positive when the ref doesnt actually exist in history anymore.

**Comment by ThomasAribart** [comment]
Hi @meeroslav @chrisui !

I have a similar issue: I deploy in prod on github release publication. The action fails to find a successful workflow.

<img width="556" alt="v1 13 0 🌈 · Sanofi-Accelerator:apdupius-front-react@1ac36f4 2022-06-10 13-27-27" src="https://user-images.githubusercontent.com/38014240/173055356-ad499469-af1a-488e-a796-5ae70fcd611c.png">

I think it is because in this case, there is no branch associated with the workflow.

<img width="791" alt="actions" src="https://user-images.githubusercontent.com/38014240/173054711-dba76a57-b6ec-4045-acf1-aef4e498a4dd.png">

My main branch is `main`, if I filter by it, you will see that the `deploy-prod` action is not found:

<img width="346" alt="Actions · Sanofi-Accelerator:apdupius-front-react 2022-06-10 13-24-28" src="https://user-images.githubusercontent.com/38014240/173054938-dedfe4cd-b022-439b-be6d-6fe294ddc599.png">

There is no current way to "unset" the `main-branch-name` input. I tried setting it to `""` but the branch name is still inferred as `false` (and I get an additional error message).

<img width="532" alt="v1 13 1 🌈 · Sanofi-Accelerator:apdupius-front-react@d15e1a1 2022-06-10 13-28-43" src="https://user-images.githubusercontent.com/38014240/173055524-113c0cca-3a02-4ef1-bc0b-63bd253450df.png">

Could we remove the default value of `main-branch-name` and set it as non-required ?

**Comment by amireldor** [comment]
Hey @ThomasAribart ,

_I'm not one of the maintainers of the repo so it's only a friendly suggestions :)_

Maybe you can use one of the GitHub actions context variables of the current running workflow for getting the git ref.

I see some examples here https://stackoverflow.com/questions/58177786/get-the-current-pushed-tag-in-github-actions or also a reference of the variables here https://docs.github.com/en/actions/learn-github-actions/contexts#github-context.

I think it might help being set as `main-branch-name` instead of 'unsetting' it. If this works then this variable's name is confusing. Please let us know if that helped, I might need this info in the future :smile:
